// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Dynamictradingstrategies

//@version=5
indicator("STOCHASTIC TRADING INDICATOR WITH ALERTS", overlay = true)

///// USER INPUTS 


periodk = input.int(defval = 14, title = "STOCHASTIC")
smoothk = input.int(defval = 3, title = "%K")
smoothd = input.int(defval = 3, title = "%D")


////// SMOOTH STOCHASTIC INDICATOR 

k = ta.sma(ta.stoch(close,high,low,periodk),smoothk)
d = ta.sma(k,smoothd)

////// BUY AND SHORT SIGNALS

buy = ta.crossover(k,d) and k < 20 and d < 20
short = ta.crossunder(k,d) and k > 80 and d > 80


//// PLOT BUY AND SHORT SIGNALS 

plotshape(buy,style = shape.triangleup,location = location.belowbar, color = color.green, size = size.small)
plotshape(short, style = shape.triangledown,location = location.abovebar, color = color.red,size = size.small)

////// 


if buy
    alert("BUY", alert.freq_once_per_bar_close)

if short
    alert("SHORT", alert.freq_once_per_bar_close)



